export const navLinks = [
  { title: "Головна", href: "/", subLinks: [] },
  {
    title: "Роботи",
    href: "/jobs",
    subLinks: [],
  },
  {
    title: "Салони",
    href: "/dealership",
    subLinks: [
      { title: "Рибffffffffffffа", href: "" },
      { title: "Ферма", href: "" },
      { title: "Інше", href: "" },
    ],
  },
  {
    title: "Скупники",
    href: "/buyers",
    subLinks: [
      { title: "Риба", href: "/fish" },
      { title: "Ферма", href: "/vegetables" },
      { title: "Інше", href: "/other" },
    ],
  },
];

export const profileLink = [
  { title: "Загальна інформація", href: "/profile" },
  { title: "Регадування профілю", href: "profile/update" },
];

export const buyers = {
  fish: [
    {
      id: "1",
      name: "Плітка",
      min: 100,
      max: 187,
      nowPrice: 151,
      percentage: 20,
    },
    {
      id: "2",
      name: "Осетр",
      min: 123,
      max: 201,
      nowPrice: 172,
      percentage: 20,
    },
    {
      id: "3",
      name: "Окунь",
      min: 197,
      max: 345,
      nowPrice: 260,
      percentage: 20,
    },
    {
      id: "3",
      name: "Щука",
      min: 180,
      max: 327,
      nowPrice: 186,
      percentage: 20,
    },
    {
      id: "4",
      name: "Сом",
      min: 470,
      max: 735,
      nowPrice: 490,
      percentage: 20,
    },
    {
      id: "5",
      name: "Судак",
      min: 430,
      max: 641,
      nowPrice: 512,
      percentage: 20,
    },
    {
      id: "6",
      name: "Головень",
      min: 156,
      max: 259,
      nowPrice: 157,
      percentage: 20,
    },
    {
      id: "7",
      name: "Головень",
      min: 156,
      max: 259,
      nowPrice: 157,
      percentage: 20,
    },
    {
      id: "8",
      name: "Карась",
      min: 90,
      max: 196,
      nowPrice: 194,
      percentage: 20,
    },
    {
      id: "9",
      name: "Линь",
      min: 243,
      max: 479,
      nowPrice: 469,
      percentage: 20,
    },
    {
      id: "10",
      name: "Зубатка",
      min: 479,
      max: 647,
      nowPrice: 581,
      percentage: 20,
    },
    {
      id: "11",
      name: "Головець",
      min: 215,
      max: 432,
      nowPrice: 334,
      percentage: 20,
    },
    {
      id: "12",
      name: "Тунець",
      min: 136,
      max: 256,
      nowPrice: 149,
      percentage: 20,
    },
    {
      id: "13",
      name: "Дорадо",
      min: 210,
      max: 429,
      nowPrice: 339,
      percentage: 20,
    },
    {
      id: "14",
      name: "Марлін",
      min: 110,
      max: 213,
      nowPrice: 135,
      percentage: 20,
    },
    {
      id: "15",
      name: "Сьомга",
      min: 180,
      max: 356,
      nowPrice: 187,
      percentage: 20,
    },
    {
      id: "16",
      name: "Пірання",
      min: 760,
      max: 1030,
      nowPrice: 896,
      percentage: 20,
    },
    {
      id: "17",
      name: "Баракуда",
      min: 512,
      max: 734,
      nowPrice: 683,
      percentage: 20,
    },
    {
      id: "18",
      name: "Золота рибка",
      min: 25000,
      max: 90000,
      nowPrice: 73853,
      percentage: 20,
    },
  ],
  vegetables: [
    {
      id: "1",
      name: "Соняшник",
      min: 39,
      max: 65,
      nowPrice: 151,
      percentage: 20,
    },
    {
      id: "2",
      name: "Ячмінь",
      min: 48,
      max: 78,
      nowPrice: 172,
      percentage: 20,
    },
    {
      id: "3",
      name: "Кукурудза",
      min: 52,
      max: 104,
      nowPrice: 260,
      percentage: 20,
    },
    {
      id: "3",
      name: "Пшениця",
      min: 16,
      max: 65,
      nowPrice: 186,
      percentage: 20,
    },
    {
      id: "4",
      name: "Картопля",
      min: 45,
      max: 91,
      nowPrice: 490,
      percentage: 20,
    },
    {
      id: "5",
      name: "Морква",
      min: 32,
      max: 65,
      nowPrice: 512,
      percentage: 20,
    },
    {
      id: "6",
      name: "Огірок",
      min: 19,
      max: 58,
      nowPrice: 157,
      percentage: 20,
    },
    {
      id: "7",
      name: "Помідор",
      min: 45,
      max: 84,
      nowPrice: 157,
      percentage: 20,
    },
    {
      id: "8",
      name: "Вишня",
      min: 143,
      max: 221,
      nowPrice: 194,
      percentage: 20,
    },
    {
      id: "9",
      name: "Журавлина",
      min: 58,
      max: 117,
      nowPrice: 469,
      percentage: 20,
    },
    {
      id: "10",
      name: "Калина",
      min: 65,
      max: 130,
      nowPrice: 581,
      percentage: 20,
    },
    {
      id: "11",
      name: "Яблуко",
      min: 52,
      max: 104,
      nowPrice: 334,
      percentage: 20,
    },
  ],
  other: [
    {
      id: "1",
      name: "Маріхуанна",
      min: 90,
      max: 161,
      nowPrice: 103,
      percentage: 20,
    },
    {
      id: "2",
      name: "Форт Занкудо",
      min: 90000,
      max: 324001,
      nowPrice: 317174,
      percentage: 20,
    },
    {
      id: "3",
      name: "Авіаносець",
      min: 110000,
      max: 486000,
      nowPrice: 317174,
      percentage: 20,
    },
  ],
};
